### ISSUE TITLE
[RFC] Move etc/packages/app.yaml contents to etc/container.yaml?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#117]
By default, in a Flex app you have this:

```yaml
# etc/packages/app.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../../src/*'
        exclude: '../../src/{Entity,Repository,Tests}'

    App\Controller\:
        resource: '../../src/Controller'
        public: true
        tags: ['controller.service_arguments']
```

```yaml
# etc/container.yaml
parameters:

services:
```

---

I propose to remove `etc/packages/app.yaml` and move its contents to `etc/container.yaml` (maybe renaming `etc/container.yaml` to `etc/app.yaml` too?)

My reasoning:

* The app.yaml file just defines container things ... so it's strange to separate it from container.yaml which defines container things too.
* If you put your own services in container.yaml ... but the _defaults config is in app.yaml ... that global config doesn't apply to container.yaml services, so it can be confusing.
* It's strange to put app.yaml inside packages/ because it's not really a package installed in the app.
