### ISSUE TITLE
Support for SensioLabsInsight?

### ISSUE THREAD

**Issue by tarlepp** [symfony/flex#136]
It seems like there isn't support for Flex for now - is this coming on someday?

Or is there a guide to configure `Symfony3 web project` project to use Flex setup?

**Comment by sstok** [comment]
Here's the custom config I'm using (and it does work):

```
pre_composer_script: "#!/bin/bash\ncp .env.dist .env\n"
rules:
    composer.unfixed_dependency_version:
        enabled: false
    web.missing_favicon:
        enabled: false
    symfony.dependency_injection.use_dir_file_constant:
        enabled: false
exclude_patterns:
    - public/index.php
    - config/bundles.php
    - 'var/*'
```
