### ISSUE TITLE
Setup as a feature tree

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/flex#167]
I thought the complete day about one idea: 
It comes from my work on Symfony CMF. There i would say that the reciepe is just a starting point. Mostly our user have to enable some configuration and requiere more dependencies (PHPCR or ORM -> depending bundles). So i would say there should kind of a tree of features under the first reciepe:

```yaml
base-reciepe:
    alias: demo
    bundles: [...]
    config: ... by copying
    features:
         feature-A:
               alias: a
               bundles: [...]
               config: ...
               dependencies: [bundle-c, bundle-d]
               features:
                        ....
         feature-B:
               alias: b
               bundles: [...]
               config: ...
               dependencies: [bundle-y, bundle-x]
```

Thinking that way it would be awesome to not only `composer req demo`, i would be really happy to do a `composer require demo:a:d`.

From my outer perspective on flex i would say it is just run down the tree and do the same on each node as is done on base repository. We only have to add some additional composer requires in between. and do a kind of a merging strategy for configuration and bundles.
