### ISSUE TITLE
[ContainerConfigurator] Duplicating parameters

### ISSUE THREAD

**Issue by rogeriolino** [symfony/flex#202]
Duplicating parameters on `config/services.yaml` when the parameter already exists in the file.

Example:

```yaml
parameters:
  locale: pt # original parameter
  locale: en # parameter added after install
```
