### ISSUE TITLE
[Question] Is it mandatory to abide to the generated configs for recipes?

### ISSUE THREAD

**Issue by benplummer** [symfony/flex#217]
Let's use the doctrine-bundle's `doctrine.yaml` as an example: https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml

Flex copies the above file and contents into place in the project and contains the following snippet:
```
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
```
Rather than having dbal configured with the whole url as shown above, it might be desired to split out the values into their own keys, for example:
```
doctrine:
    dbal:
        driver: '%env(resolve:DATABASE_DRIVER)%'
        charset: '%env(resolve:DATABASE_CHARSET)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        host: '%env(resolve:DATABASE_HOST)%'
```
This allows each individual database credential to be set in the `.env`, or as many as are desired, rather than all of them together as a URL.

Based on the above...

1. Is it fine to replace any recipe generated configuration with configuration of your own preference for that package?

2. Are there any downsides to doing this?

3. If the package is updated in the future, or any other related composer process is run on it, could the altered configuration be overwritten? Or does configuration only get written on `require`?

I assume these questions also rely on the generated code inside the `.env` file too.

Thanks
